/* Plugin generated by AMXX-Studio */

#include <amxmodx>
#include <amxmisc>
#include <hamsandwich>
#include <cstrike>
#include <fakemeta>
#include <fun>
#include <nvault>
#include <engine>
#include <colorchat>
#include <jail>
#include <csx>

#define PLUGIN "Lonca"
#define VERSION "1.0"
#define AUTHOR "Berat Nzp"

new tagplugin[]="^4[^1Lonca^4]"
new vgoster[]="1.0"

new loncamevcut[33];
new loncadegistirme[33];
new oyuncupuan[33];
new yeniayrilma[33];

new lonca1[]="The Rookies" // Caylaklar
new lonca2[]="The Killers" // Katiller
new lonca3[]="The Destroyers" // Yýkýcýlar
new lonca4[]="The Royals" // Kraliyet Ailesi

new lonca1tag[]="TR"
new lonca2tag[]="TK"
new lonca3tag[]="TD"
new lonca4tag[]="***"

new lonca1kayit[33];
new lonca2kayit[33];
new lonca3kayit[33];
new lonca4kayit[33];

new lonca1seviye=0;
new lonca2seviye=0;
new lonca3seviye=0;
new lonca4seviye=0;

new lonca1puan;
new lonca2puan;
new lonca3puan;
new lonca4puan;

new lonca1mevcut;
new lonca2mevcut;
new lonca3mevcut;
new lonca4mevcut;

new olen;
new olduren;
new headshoot;

new loncadegis;
new killpointsys;
new playerkillpoint;
new playerkillhspoint;
new killpoint;
new killhspoint;
new suicidepoint;

const MENU_TUSLARI = MENU_KEY_0|MENU_KEY_1|MENU_KEY_2|MENU_KEY_3|MENU_KEY_4|MENU_KEY_5|MENU_KEY_6|MENU_KEY_7|MENU_KEY_8|MENU_KEY_9|MENU_KEY_0

public plugin_init()
{
	register_plugin(PLUGIN, VERSION, AUTHOR)
	
	register_clcmd("say /lonca","loncasys")
	register_clcmd("loncaquit","loncaayril")
	
	loncadegis	= register_cvar("lonca_degis"	, "4")
	killpointsys	= register_cvar("lonca_puan"	, "100")
	
	register_menu("loncasysmenu",MENU_TUSLARI,"loncasysislem")
	register_menu("loncabilgi",MENU_TUSLARI,"loncabilgiislem")
	
	RegisterHam(Ham_Spawn,"player","Fwd_PlayerSpawn_Post",1)
	register_event("DeathMsg",	"eDeath",	"a")
	//RegisterHam(Ham_Killed,"player","fw_player_killed")
}

public client_putinserver(id)
{
	loncamevcut[id]		= 0;
	loncadegistirme[id]	= get_pcvar_num(loncadegis)
	oyuncupuan[id]		= 0;
	yeniayrilma[id]		= 0;
	
	lonca1kayit[id]		= 0;
	lonca2kayit[id]		= 0;
	lonca3kayit[id]		= 0;
	lonca4kayit[id]		= 0;
}

public client_disconnect(client)
{
	if(lonca1kayit[client]==1)
	{
		lonca1mevcut	-=1;
	}
	if(lonca2kayit[client]==1)
	{
		lonca2mevcut	-=1;
	}
	if(lonca3kayit[client]==1)
	{
		lonca3mevcut	-=1;
	}
	if(lonca4kayit[client]==1)
	{
		lonca4mevcut	-=1;
	}
}

public seviyekontrol()
{
	if(lonca1puan<1000)
	{
		lonca1seviye=0
	}
	if(lonca1puan>=1000)
	{
		lonca1seviye=1
	}
	if(1000<lonca1puan>=2500)
	{
		lonca1seviye=2
	}
	if(2500<lonca1puan>=4500)
	{
		lonca1seviye=3
	}
	if(4500<lonca1puan>=7000)
	{
		lonca1seviye=4
	}
	if(7000<lonca1puan>=10000)
	{
		lonca1seviye=5
	}
	//////////////////////////////////////////////////////////////////////////////////////////////
	if(lonca2puan<1000)
	{
		lonca2seviye=0
	}
	if(lonca2puan>=1000)
	{
		lonca2seviye=1
	}
	if(1000<lonca2puan>=2500)
	{
		lonca2seviye=2
	}
	if(2500<lonca2puan>=4500)
	{
		lonca2seviye=3
	}
	if(4500<lonca2puan>=7000)
	{
		lonca2seviye=4
	}
	if(7000<lonca2puan>=10000)
	{
		lonca2seviye=5
	}
	//////////////////////////////////////////////////////////////////////////////////////////////
	if(lonca3puan<1000)
	{
		lonca3seviye=0
	}
	if(lonca3puan>=1000)
	{
		lonca3seviye=1
	}
	if(1000<lonca3puan>=2500)
	{
		lonca3seviye=2
	}
	if(2500<lonca3puan>=4500)
	{
		lonca3seviye=3
	}
	if(4500<lonca3puan>=7000)
	{
		lonca3seviye=4
	}
	if(7000<lonca3puan>=10000)
	{
		lonca3seviye=5
	}
	//////////////////////////////////////////////////////////////////////////////////////////////
	if(lonca4puan>=0)
	{
		lonca4seviye=10
	}	
}

public eDeath()
{
	olduren = read_data(1);
	olen = read_data(2);
	headshoot = read_data(3);
	
	playerkillpoint		= get_pcvar_num(killpointsys);
	playerkillhspoint	= playerkillpoint/2;
	killpoint		= playerkillpoint+playerkillpoint;
	killhspoint		= playerkillhspoint+playerkillhspoint;
	suicidepoint		= playerkillpoint/4
	new aname[32],bname[32];
	get_user_name(olduren,aname,31);
	get_user_name(olen,bname,31);
	
	seviyekontrol();
	seviyekontrol();
	seviyekontrol();
	
	if(cs_get_user_team(olen)==CS_TEAM_T&&cs_get_user_team(olduren)==CS_TEAM_CT)
	{
		if(loncamevcut[olen]==1)
		{
			if(lonca1kayit[olen]==1)
			{
				lonca1puan	-= suicidepoint;
				ColorChat(0,NORMAL,"^4[^1%s^4] ^3%s^1 loncamiza ^4%d^1 puan kaybettirmistir. Seviyemiz:^4%d ^1Puanimiz:^4%d",lonca1tag,bname,suicidepoint,lonca1seviye,lonca1puan);
			}
			if(lonca2kayit[olen]==1)
			{
				lonca2puan	-= suicidepoint;
				ColorChat(0,NORMAL,"^4[^1%s^4] ^3%s^1 loncamiza ^4%d^1 puan kaybettirmistir. Seviyemiz:^4%d ^1Puanimiz:^4%d",lonca2tag,bname,suicidepoint,lonca2seviye,lonca2puan);
			}
			if(lonca3kayit[olen]==1)
			{
				lonca3puan	-= suicidepoint;
				ColorChat(0,NORMAL,"^4[^1%s^4] ^3%s^1 loncamiza ^4%d^1 puan kaybettirmistir. Seviyemiz:^4%d ^1Puanimiz:^4%d",lonca3tag,bname,suicidepoint,lonca3seviye,lonca3puan);
			}
			if(lonca4kayit[olen]==1)
			{
				lonca4puan	-= suicidepoint;
				ColorChat(0,NORMAL,"^4[^1%s^4] ^3%s^1 loncamiza ^4%d^1 puan kaybettirmistir. Seviyemiz:^4%d ^1Puanimiz:^4%d",lonca4tag,bname,suicidepoint,lonca4seviye,lonca4puan);
			}
		}
	}
	
	if(cs_get_user_team(olen)==CS_TEAM_CT)
	{
		if(loncamevcut[olduren]==1)
		{
			if(lonca1kayit[olduren]==1)
			{
				oyuncupuan[olduren]+=playerkillpoint;
				lonca1puan+=killpoint;
				ColorChat(0,NORMAL,"^4[^1%s^4] ^3%s^1 loncamiza ^4%d^1 puan kazandirmistir. Seviyemiz:^4%d ^1Puanimiz:^4%d",lonca1tag,aname,killpoint,lonca1seviye,lonca1puan);
				if(headshoot)
				{
					oyuncupuan[olduren]+=playerkillhspoint;
					lonca1puan+=killhspoint;
					ColorChat(0,NORMAL,"^4[^1%s^4] ^3%s^1 loncamiza +^4%d^1 daha puan kazandirmistir. Seviyemiz:^4%d ^1Puanimiz:^4%d",lonca1tag,aname,killhspoint,lonca1seviye,lonca1puan);
				}
			}
		}
		//////////////////////////////////////////////////////////////////////////////////////////////
		if(loncamevcut[olduren]==1)
		{
			if(lonca2kayit[olduren]==1)
			{
				oyuncupuan[olduren]+=playerkillpoint;
				lonca2puan+=killpoint;
				ColorChat(0,NORMAL,"^4[^1%s^4] ^3%s^1 loncamiza ^4%d^1 puan kazandirmistir. Seviyemiz:^4%d ^1Puanimiz:^4%d",lonca2tag,aname,killpoint,lonca2seviye,lonca2puan);
				if(headshoot)
				{
					oyuncupuan[olduren]+=playerkillhspoint;
					lonca2puan+=killhspoint;
					ColorChat(0,NORMAL,"^4[^1%s^4] ^3%s^1 loncamiza +^4%d^1 daha puan kazandirmistir. Seviyemiz:^4%d ^1Puanimiz:^4%d",lonca2tag,aname,killhspoint,lonca2seviye,lonca2puan);
				}
			}
		}
		//////////////////////////////////////////////////////////////////////////////////////////////
		if(loncamevcut[olduren]==1)
		{
			if(lonca3kayit[olduren]==1)
			{
				oyuncupuan[olduren]+=playerkillpoint;
				lonca3puan+=killpoint;
				ColorChat(0,NORMAL,"^4[^1%s^4] ^3%s^1 loncamiza ^4%d^1 puan kazandirmistir. Seviyemiz:^4%d ^1Puanimiz:^4%d",lonca3tag,aname,killpoint,lonca3seviye,lonca3puan);
				if(headshoot)
				{
					oyuncupuan[olduren]+=playerkillhspoint;
					lonca3puan+=killhspoint;
					ColorChat(0,NORMAL,"^4[^1%s^4] ^3%s^1 loncamiza +^4%d^1 daha puan kazandirmistir. Seviyemiz:^4%d ^1Puanimiz:^4%d",lonca3tag,aname,killhspoint,lonca3seviye,lonca3puan);
				}
			}
		}
		////////////////////////////////////////////////////////////////////////////////////////
		if(loncamevcut[olduren]==1)
		{
			if(lonca4kayit[olduren]==1)
			{
				oyuncupuan[olduren]+=playerkillpoint;
				lonca4puan+=killpoint;
				ColorChat(0,NORMAL,"^4[^1%s^4] ^3%s^1 loncamiza ^4%d^1 puan kazandirmistir. Seviyemiz:^4%d ^1Puanimiz:^4%d",lonca4tag,aname,killpoint,lonca4seviye,lonca4puan);
				if(headshoot)
				{
					oyuncupuan[olduren]+=playerkillhspoint;
					lonca4puan+=killhspoint;
					ColorChat(0,NORMAL,"^4[^1%s^4] ^3%s^1 loncamiza +^4%d^1 daha puan kazandirmistir. Seviyemiz:^4%d ^1Puanimiz:^4%d",lonca4tag,aname,killhspoint,lonca4seviye,lonca4puan);
				}
			}
		}
		loncasys(olduren);
	}
}

public Fwd_PlayerSpawn_Post(id)
{
	if(cs_get_user_team(id)==CS_TEAM_CT)
	{
		loncamevcut[id]		= 0;
		loncadegistirme[id]	= get_pcvar_num(loncadegis)
		//oyuncupuan[id]		= 0;
		yeniayrilma[id]		= 0;
		
		if(lonca1kayit[id]==1)
		{
			lonca1kayit[id]	= 0;
			lonca1mevcut	-= 1;
		}
		if(lonca2kayit[id]==1)
		{
			lonca2kayit[id]	= 0;
			lonca2mevcut	-= 1;
		}
		if(lonca3kayit[id]==1)
		{
			lonca3kayit[id]	= 0;
			lonca3mevcut	-= 1;
		}
		if(lonca4kayit[id]==1)
		{
			lonca4kayit[id]	= 0;
			lonca4mevcut	-= 1;
		}
	}
	
	if(loncamevcut[id]<1&&cs_get_user_team(id)==CS_TEAM_T)
	{
		ColorChat(id,NORMAL,"%s ^1Hicbir loncada bulunmadiginiz icin extra ozellikler gelmedi. Loncalara katilmak icin ^3^"/lonca^"^1 yazin.",tagplugin);
	}
	
	if(loncamevcut[id]==1)
	{
		if(lonca1kayit[id]==1)
		{
			if(lonca1seviye==1)
			{
				set_user_health(id,105)
			}
			if(lonca1seviye==2)
			{
				set_user_health(id,110)
			}
			if(lonca1seviye==3)
			{
				set_user_health(id,115)
			}
			if(lonca1seviye==4)
			{
				set_user_health(id,120)
			}
			if(lonca1seviye==5)
			{
				set_user_health(id,125)
			}
		}
		//////////////////////////////////////////////////////////////////////////////////////////////
		if(lonca2kayit[id]==1)
		{
			if(lonca2seviye==1)
			{
				set_task(3.0,"speedver",id)
			}
			if(lonca2seviye==2)
			{
				set_task(3.0,"speedver",id)
			}
			if(lonca2seviye==3)
			{
				set_task(3.0,"speedver",id)
			}
			if(lonca2seviye==4)
			{
				set_task(3.0,"speedver",id)
			}
			if(lonca2seviye==5)
			{
				set_task(3.0,"speedver",id)
			}
		}
		//////////////////////////////////////////////////////////////////////////////////////////////
		if(lonca3kayit[id]==1)
		{
			if(lonca3seviye==1)
			{
				set_user_health(id,105)
			}
			if(lonca3seviye==2)
			{
				set_user_health(id,110)
			}
			if(lonca3seviye==3)
			{
				set_user_health(id,115)
			}
			if(lonca3seviye==4)
			{
				set_user_health(id,120)
			}
			if(lonca3seviye==5)
			{
				set_user_health(id,125)
			}
		}
		//////////////////////////////////////////////////////////////////////////////////////////////
		if(lonca4kayit[id]==1)
		{
			set_user_health(id,125)
			set_task(3.0,"speedver",id)
		}
	}
}

public speedver(id)
{
	if(lonca2kayit[id]==1)
	{
		if(lonca1seviye==1)
		{
			set_user_maxspeed(id,275.0)
		}
		if(lonca1seviye==2)
		{
			set_user_maxspeed(id,300.0)
		}
		if(lonca1seviye==3)
		{
			set_user_maxspeed(id,325.0)
		}
		if(lonca1seviye==4)
		{
			set_user_maxspeed(id,350.0)
		}
		if(lonca1seviye==5)
		{
			set_user_maxspeed(id,375.0)
		}
	}
	if(lonca4kayit[id]==1)
	{
		set_user_maxspeed(id,375.0)
	}
}

public loncasys(id)
{
	if(cs_get_user_team(id)==CS_TEAM_T)
	{
		new pname[32];
		get_user_name(id,pname,31);
		static MenuSys1[512],satir;
		satir=0;
		
		satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\d. :\wLonca \r%s\d: .^n",vgoster);
		satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\rMerhaba; \d%s^n",pname);
		
		if(loncamevcut[id]==0)
		{
			satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\rTecrube Puaniniz: \d%d^n",oyuncupuan[id]);
			satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"^n");
			satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\wLonca Secin");
			satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"^n");
			satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\w1. \y%s \d(%d)^n",lonca1,lonca1mevcut);
			satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\w2. \y%s \d(%d)^n",lonca2,lonca2mevcut);
			satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\w3. \y%s \d(%d)^n",lonca3,lonca3mevcut);
			satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\w4. \y%s \d(%d)^n",lonca4,lonca4mevcut);
		}
		
		if(loncamevcut[id]==1)
		{
			//////////////////////////////////////////////////////////////////////////////////////////////
			if(lonca1kayit[id]==1)
			{
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"^n");
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\rLoncaniz: \d%s (%d)^n",lonca1,lonca1mevcut);
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"^n");
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\rLonca Puani: \d%d^n",lonca1puan);
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\rLonca Seviyesi: \d%d^n",lonca1seviye);
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\rTecrube Puaniniz: \y%d^n",oyuncupuan[id]);
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"^n");
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\w8. \yLoncalari goster^n");
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\w9. \yLoncadan Ayril^n");
			}
			//////////////////////////////////////////////////////////////////////////////////////////////
			if(lonca2kayit[id]==1)
			{
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"^n");
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\rLoncaniz: \d%s (%d)^n",lonca2,lonca2mevcut);
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"^n");
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\rLonca Puani: \d%d^n",lonca2puan);
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\rLonca Seviyesi: \d%d^n",lonca2seviye);
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\rTecrube Puaniniz: \y%d^n",oyuncupuan[id]);
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"^n");
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\w8. \yLoncalari goster^n");
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\w9. \yLoncadan Ayril^n");
			}
			//////////////////////////////////////////////////////////////////////////////////////////////
			if(lonca3kayit[id]==1)
			{
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"^n");
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\rLoncaniz: \d%s (%d)^n",lonca3,lonca3mevcut);
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"^n");
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\rLonca Puani: \d%d^n",lonca3puan);
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\rLonca Seviyesi: \d%d^n",lonca3seviye);
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\rTecrube Puaniniz: \y%d^n",oyuncupuan[id]);
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"^n");
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\w8. \yLoncalari goster^n");
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\w9. \yLoncadan Ayril^n");
			}
			//////////////////////////////////////////////////////////////////////////////////////////////
			if(lonca4kayit[id]==1)
			{
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"^n");
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\rLoncaniz: \d%s (%d)^n",lonca4,lonca4mevcut);
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"^n");
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\rLonca Puani: \d%d^n",lonca4puan);
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\rLonca Seviyesi: \d%d^n",lonca4seviye);
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\rTecrube Puaniniz: \y%d^n",oyuncupuan[id]);
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"^n");
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\w8. \yLoncalari goster^n");
				satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\w9. \yLoncadan Ayril^n");
			}
			//////////////////////////////////////////////////////////////////////////////////////////////
		}
		satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"^n");
		satir+=formatex(MenuSys1[satir],charsmax(MenuSys1)-satir,"\w0. Kapat");
		show_menu(id,MENU_TUSLARI,MenuSys1,-1,"loncasysmenu");
	}
	return PLUGIN_HANDLED;
}


public loncasysislem(id,bind1)
{
	new pname[32];
	get_user_name(id,pname,31);
	switch(bind1)
	{
		case 0:
		{
			if(loncamevcut[id]<1&&loncadegistirme[id]>=1)
			{
				loncamevcut[id]		= 1;
				loncadegistirme[id]	-=1;
				yeniayrilma[id]		= 0;
				
				lonca1kayit[id]		= 1;
				lonca1mevcut		+=1;
				lonca2kayit[id]		= 0;
				lonca3kayit[id]		= 0;
				lonca4kayit[id]		= 0;
				
				ColorChat(0,NORMAL,"%s ^3%s^1 nickli oyuncu ^3%s^1 loncasina katildi !",tagplugin,pname,lonca1);
				loncasys(id);
			}
			//////////////////////////////////////////////////////////////////////////////////////////////
			if(loncadegistirme[id]<1)
			{
				ColorChat(id,NORMAL,"%s ^1En fazla ^4%d^1 defa lonca degistirebilirsiniz.",get_pcvar_num(loncadegis))
			}
		}
		//////////////////////////////////////////////////////////////////////////////////////////////
		case 1:
		{
			if(loncamevcut[id]<1&&loncadegistirme[id]>=1)
			{
				loncamevcut[id]		= 1;
				loncadegistirme[id]	-=1;
				yeniayrilma[id]		= 0;
				
				lonca1kayit[id]		= 0;
				lonca2kayit[id]		= 1;
				lonca2mevcut		+=1;
				lonca3kayit[id]		= 0;
				lonca4kayit[id]		= 0;
				
				ColorChat(0,NORMAL,"%s ^3%s^1 nickli oyuncu ^3%s^1 loncasina katildi !",tagplugin,pname,lonca2);
				loncasys(id);
			}
			//////////////////////////////////////////////////////////////////////////////////////////////
			if(loncadegistirme[id]<1)
			{
				ColorChat(id,NORMAL,"%s ^1En fazla ^4%d^1 defa lonca degistirebilirsiniz.",get_pcvar_num(loncadegis))
			}
		}
		//////////////////////////////////////////////////////////////////////////////////////////////
		case 2:
		{
			if(loncamevcut[id]<1&&loncadegistirme[id]>=1)
			{
				loncamevcut[id]		= 1;
				loncadegistirme[id]	-=1;
				yeniayrilma[id]		= 0;
				
				lonca1kayit[id]		= 0;
				lonca2kayit[id]		= 0;
				lonca3kayit[id]		= 1;
				lonca3mevcut		+=1;
				lonca4kayit[id]		= 0;
				
				ColorChat(0,NORMAL,"%s ^3%s^1 nickli oyuncu ^3%s^1 loncasina katildi !",tagplugin,pname,lonca3);
				loncasys(id);
			}
			//////////////////////////////////////////////////////////////////////////////////////////////
			if(loncadegistirme[id]<1)
			{
				ColorChat(id,NORMAL,"%s ^1En fazla ^4%d^1 defa lonca degistirebilirsiniz.",get_pcvar_num(loncadegis))
			}
		}
		//////////////////////////////////////////////////////////////////////////////////////////////
		case 3:
		{
			if(loncamevcut[id]<1&&loncadegistirme[id]>=1&&oyuncupuan[id]>=15000)
			{
				loncamevcut[id]		= 1;
				loncadegistirme[id]	-=1;
				yeniayrilma[id]		= 0;
				
				lonca1kayit[id]		= 0;
				lonca2kayit[id]		= 0;
				lonca3kayit[id]		= 0;
				lonca4kayit[id]		= 1;
				lonca4mevcut		+=1;
				
				ColorChat(0,NORMAL,"%s ^3%s^1 nickli oyuncu ^3%s^1 loncasina katildi !",tagplugin,pname,lonca4);
				loncasys(id);
			}
			//////////////////////////////////////////////////////////////////////////////////////////////
			if(loncadegistirme[id]<1)
			{
				ColorChat(id,NORMAL,"%s ^1En fazla ^4%d^1 defa lonca degistirebilirsiniz.",get_pcvar_num(loncadegis));
			}
			if(oyuncupuan[id]<25000)
			{
				ColorChat(id,NORMAL,"%s Loncamiza katilabilmek icin en az^3 15.000 TP^1'niz olmalidir.",tagplugin);
			}
		}
		case 7:
		{
			loncabilgi(id);
		}
		case 8:
		{
			if(loncamevcut[id]==1)
			{
				loncaayril(id);
				loncasys(id);
			}
		}
	}
}

public loncaayril(id)
{
	new pname[32];
	get_user_name(id,pname,31);
	if(loncamevcut[id]==1)
	{
		if(lonca1kayit[id]==1)
		{
			lonca1kayit[id]		= 0;
			loncamevcut[id]		= 0;
			yeniayrilma[id]		= 1;
			lonca1mevcut		-=1;
			ColorChat(0,NORMAL,"%s ^3%s^1 nickli oyuncu ^3%s^1 loncasindan ayrildi !",tagplugin,pname,lonca1);

		}
		//////////////////////////////////////////////////////////////////////////////////////////////
		if(lonca2kayit[id]==1)
		{
			lonca2kayit[id]		= 0;
			loncamevcut[id]		= 0;
			yeniayrilma[id]		= 1;
			lonca2mevcut		-=1;
			ColorChat(0,NORMAL,"%s ^3%s^1 nickli oyuncu ^3%s^1 loncasindan ayrildi !",tagplugin,pname,lonca2);

		}
		//////////////////////////////////////////////////////////////////////////////////////////////
		if(lonca3kayit[id]==1)
		{
			lonca3kayit[id]		= 0;
			loncamevcut[id]		= 0;
			yeniayrilma[id]		= 1;
			lonca3mevcut		-=1;
			ColorChat(0,NORMAL,"%s ^3%s^1 nickli oyuncu ^3%s^1 loncasindan ayrildi !",tagplugin,pname,lonca3);
		}
		//////////////////////////////////////////////////////////////////////////////////////////////
		if(lonca4kayit[id]==1)
		{
			lonca4kayit[id]		= 0;
			loncamevcut[id]		= 0;
			yeniayrilma[id]		= 1;
			lonca4mevcut		-=1;
			ColorChat(0,NORMAL,"%s ^3%s^1 nickli oyuncu ^3%s^1 loncasindan ayrildi !",tagplugin,pname,lonca4);
		}
	}
	//////////////////////////////////////////////////////////////////////////////////////////////
	if(loncamevcut[id]==0&&yeniayrilma[id]==0)
	{
		ColorChat(id,NORMAL,"%s Zaten hicbir loncada degilsiniz.",tagplugin);
	}
	return PLUGIN_HANDLED;
}

public loncabilgi(id)
{
	new pname[32];
	get_user_name(id,pname,31);
	if(loncamevcut[id]==1)
	{
		static MenuSys2[512],satirx;
		satirx=0;
		
		satirx+=formatex(MenuSys2[satirx],charsmax(MenuSys2)-satirx,"\d. :\wLonca \r%s\d: .^n",vgoster);
		satirx+=formatex(MenuSys2[satirx],charsmax(MenuSys2)-satirx,"\rMerhaba; \d%s^n",pname);
		
		satirx+=formatex(MenuSys2[satirx],charsmax(MenuSys2)-satirx,"^n");
		
		satirx+=formatex(MenuSys2[satirx],charsmax(MenuSys2)-satirx,"\y%s \d(%d)^n",lonca1,lonca1mevcut);
		satirx+=formatex(MenuSys2[satirx],charsmax(MenuSys2)-satirx,"\y%s \d(%d)^n",lonca2,lonca2mevcut);
		satirx+=formatex(MenuSys2[satirx],charsmax(MenuSys2)-satirx,"\y%s \d(%d)^n",lonca3,lonca3mevcut);
		satirx+=formatex(MenuSys2[satirx],charsmax(MenuSys2)-satirx,"\y%s \d(%d)^n",lonca4,lonca4mevcut);
		
		satirx+=formatex(MenuSys2[satirx],charsmax(MenuSys2)-satirx,"^n");
		satirx+=formatex(MenuSys2[satirx],charsmax(MenuSys2)-satirx,"\w0. Kapat");
		show_menu(id,MENU_TUSLARI,MenuSys2,-1,"loncabilgimenu");
	}
	return PLUGIN_HANDLED;
}

public loncabilgiislem(id,bind2)
{
	switch(bind2)
	{
		case 0:
		{
			loncabilgi(id);
		}
		case 1:
		{
			loncabilgi(id);
		}
		case 2:
		{
			loncabilgi(id);
		}
		case 3:
		{
			loncabilgi(id);
		}
	}
}
